name: velozaje
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter 
  
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  dotted_border: ^3.1.0
  icons_plus: ^5.0.0
  camera: ^0.11.3
  share_plus: ^12.0.1
  easy_stepper: ^0.9.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  
  uses-material-design: true

  assets:
    - assest/nav/
    - assest/image/
    - assest/icon/
    - assest/badge/
   